### ISSUE TITLE
Add Database Properties to the Admin experience

### ISSUE THREAD

**Issue by ssreerama** [microsoft/sqltoolsservice#2113]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/sqltoolsservice/issues/2114
- [ ] https://github.com/microsoft/sqltoolsservice/issues/2115
- [ ] https://github.com/microsoft/sqltoolsservice/issues/2148
- [ ] https://github.com/microsoft/sqltoolsservice/issues/2180
- [ ] https://github.com/microsoft/sqltoolsservice/issues/2195
- [ ] https://github.com/microsoft/sqltoolsservice/issues/2212
```
